prueba/Pages/Consulta.cshtml.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Oracle.ManagedDataAccess.Client;

namespace prueba.Pages
{
    public class ConsultaModel : PageModel
    {
        ///CONFIGURACION PARA RECUPERAR DEL SETTINGS
        private IConfiguration Configuration;
    
        public ConsultaModel(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        ///FIN CONFIGURACION PARA RECUPERAR DEL SETTINGS

        public string Msg { get; set; }
        public string Mensaje { get; set; }

        public void OnPostRazonSocial(string txtNit)
        {
            ///CONFIGURACION PARA RECUPERAR DEL SETTINGS
            string connString = this.Configuration.GetConnectionString("ConexionOracleXSIN");

            string Nit = txtNit;

            if(!string.IsNullOrEmpty(Nit))
            {
                var queryString= string.Format("SELECT DENOMINACION_VC FROM VPDR_DATOS_CONTRIBUYENTES WHERE NIT_NB = " + Nit);

                using (OracleConnection connection = new OracleConnection(connString))
                {
                    try
                    {
                        connection.Open();
                        
                        OracleGlobalization info = connection.GetSessionInfo();
                        info.TimeZone = "America/La_Paz";
                        connection.SetSessionInfo(info);

                        Msg = "Conexión válida";
                        OracleCommand command = new OracleCommand(queryString, connection);
                        OracleDataReader reader = command.ExecuteReader();
                        if (reader.HasRows)
                        {
                            while (reader.Read())
                            {
                                Msg = reader.GetString(0);
                            }
                        }
                        else
                        {
                            Msg = "Sin resultados.";
                        }
                        reader.Close();
                    }
                    catch (Exception exception)
                    {
                        Msg = exception.Message;
                    }
                }
            }
            else
            {
                Msg = "Debe Ingresar un Nro de NIT...";
            }

            //Mensaje = Nit + " -- " + connString;

            Mensaje = Nit;

        }

        public void OnPostDireccion(string txtNit)
        {
            string Nit = txtNit;

            

            if(!string.IsNullOrEmpty(Nit))
            {
                var queryString= string.Format("SELECT DIRECCION_VC FROM VPDR_DATOS_CONTRIBUYENTES WHERE NIT_NB = " + Nit);

                using (OracleConnection connection = new OracleConnection("Data Source=(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (COMMUNITY = tcp.world)(PROTOCOL = TCP)(Host = 10.1.7.236)(Port = 1551))(ADDRESS = (COMMUNITY = tcp.world)(PROTOCOL = TCP)(Host = 10.1.7.236)(Port = 1551)))(CONNECT_DATA =  (SID = sin)));User Id=DDS;Password=!xyz789;Persist Security Info=True;Min Pool Size=10;Connection Lifetime=120;Connection Timeout=60;Incr Pool Size=5;Decr Pool Size=2;"))
                {
                    try
                    {
                        connection.Open();
                        Msg = "Conexión válida";
                        OracleCommand command = new OracleCommand(queryString, connection);
                        OracleDataReader reader = command.ExecuteReader();
                        if (reader.HasRows)
                        {
                            while (reader.Read())
                            {
                                Msg = reader.GetString(0);
                                //return Msg;
                            }
                        }
                        else
                        {
                            Msg = "Sin resultados.";
                            //return Msg;
                        }
                        reader.Close();
                    }
                    catch (Exception exception)
                    {
                        Msg = exception.Message;
                        //return Msg;
                    }
                    //return Msg;
                }

            }
            else
            {
                Msg = "Debe Ingresar un Nro de NIT...";
            }

            Mensaje = Nit;

        }
        
        public void OnPostTelefono(string txtNit)
        {
            string Nit = txtNit;

            if(!string.IsNullOrEmpty(Nit))
            {
            
                var queryString= string.Format("SELECT TELEFONO_1_VC FROM VPDR_DATOS_CONTRIBUYENTES WHERE NIT_NB = " + Nit);

                using (OracleConnection connection = new OracleConnection("Data Source=(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (COMMUNITY = tcp.world)(PROTOCOL = TCP)(Host = 10.1.7.236)(Port = 1551))(ADDRESS = (COMMUNITY = tcp.world)(PROTOCOL = TCP)(Host = 10.1.7.236)(Port = 1551)))(CONNECT_DATA =  (SID = sin)));User Id=DDS;Password=!xyz789;Persist Security Info=True;Min Pool Size=10;Connection Lifetime=120;Connection Timeout=60;Incr Pool Size=5;Decr Pool Size=2;"))
                {
                    try
                    {
                        connection.Open();
                        Msg = "Conexión válida";
                        OracleCommand command = new OracleCommand(queryString, connection);
                        OracleDataReader reader = command.ExecuteReader();
                        if (reader.HasRows)
                        {
                            while (reader.Read())
                            {
                                Msg = reader.GetString(0);
                                //return Msg;
                            }
                        }
                        else
                        {
                            Msg = "Sin resultados.";
                            //return Msg;
                        }
                        reader.Close();
                    }
                    catch (Exception exception)
                    {
                        Msg = exception.Message;
                        //return Msg;
                    }
                    //return Msg;
                }

            }
            else
            {
                Msg = "Debe Ingresar un Nro de NIT...";
            }

            Mensaje = Nit;
            
        }

    }
}

prueba/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace prueba.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

prueba/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace prueba.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

prueba/Pages/Consulta.cshtml
@page
@model ConsultaModel
@{
    ViewData["Title"] = "Pagina de Consultas Prueba";
}
<h1>@ViewData["Title"]</h1>


    <form method="post" asp-page="Consulta">
        <input type="text" name="txtNit" placeholder="Nro de Nit"/>
        <input type="submit" value="Razon Social" asp-page-handler="RazonSocial" />
        <input type="submit" value="Dirección" asp-page-handler="Direccion" />
        <input type="submit" value="Teléfono" asp-page-handler="Telefono" />
    </form>
    <br />
    @Model.Msg
    <br />
    <br />
    Nro de NIT: 
    @Model.Mensaje

prueba/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido al SIN</h1>
    <p>Página de Prueba CICD</p>
    <p>Otra prueba deploy en nuevo cluster net</p>
</div>

prueba/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - prueba</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Página de Prueba</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/prueba
                            /Consulta">Consulta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Servicio de Impuestos Nacionales<a asp-area="" asp-page="/Consulta"></a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>